### ISSUE TITLE
Update minimum futures market deposit

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#1380] opened 2022-09-13 05:37 UTC
Currently users are required to deposit a minimum of $50 on each futures market deposit but this should be changed to take into consideration the amount of balance already in the market. So for example if there is $25 of margin left in the market then a minimum of $25 is required when depositing.

**Comment by platschi** [comment] 2022-09-20 11:58
Duplicate of #1394

**Closed** 2022-09-20 11:57 UTC
Labels: core dev
