### ISSUE TITLE
Fix "Buying power"

### ISSUE THREAD

**Issue by Tburm** [Kwenta/kwenta#945] opened 2022-06-03 15:54 UTC
Buying power calculation right now shows `total margin * max leverage`

This is incorrect if a user has a position open. It always shows their _max_ buying power but doesn't their current position into account. Formula should be `available margin * max leverage`

- [ ] Fix buying power formula

**Comment by platschi** [comment] 2022-06-03 16:41
duplicate of #944

**Closed by platschi** 2022-06-03 16:41 UTC
